version: "3"
services:
  app:
    container_name: se00g0_app
    build:
      context: ../../
      dockerfile: ./docker/production/java/Dockerfile
      cache_from:
        - onyx.u-gakugei.ac.jp/se00g0_app:latest
    image: onyx.u-gakugei.ac.jp/se00g0_app

  mysql:
    container_name: se00g0_db
    build:
      context: ../../
      dockerfile: ./docker/production/mysql/Dockerfile
      cache_from:
        - onyx.u-gakugei.ac.jp/se00g0_db:latest
    image: onyx.u-gakugei.ac.jp/se00g0_db
